In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
x = np.array([1,2,"1"])
x.dtype

dtype('<U11')

In [3]:
classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

list

In [4]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [5]:
numpy_array.shape

(6,)

In [6]:
np.array([2,4]).mean()

3.0

In [7]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [8]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])


In [9]:
matrix1[0, :]

array([1, 2, 3])

In [10]:
matrix1[:, -1]

array([3, 6, 9])

In [11]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

In [12]:
matrix2.sum()

47

In [13]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [14]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [15]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [16]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])

#### Ćwiczenie: wektory

In [23]:
np.array([1,2,3,4,5,6,7,8,9,10]) + np.repeat(1, 10)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Ćwiczenie: macierze

In [24]:
matrix3 = np.array([
	[1,2,3,4,5],
	[6,7,8,9,10],
	[11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
np.average(matrix3, axis=0)


array([11., 12., 13., 14., 15.])

In [25]:
np.average(matrix3, axis=1)

array([ 3.,  8., 13., 18., 23.])